# Generated by Django 4.1.7 on 2023-03-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_cadastro_data_do_processo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero_do_processo',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='responsavel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
