# Generated by Django 4.1.7 on 2023-03-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_image_cadastro_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
