# Generated by Django 4.1.7 on 2023-03-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_remove_cadastro_images_alter_image_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
