# Generated by Django 4.1.7 on 2023-03-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_cadastro_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='imagem',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='imagens',
            field=models.ManyToManyField(to='cadastro.imagem'),
        ),
    ]
