# Generated by Django 4.1.7 on 2023-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_remove_cadastro_imagens_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='imagens',
            field=models.ManyToManyField(to='cadastro.imagem'),
        ),
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
