# Generated by Django 4.1.7 on 2023-04-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_cadastro_imagens_delete_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='imagens',
        ),
        migrations.AddField(
            model_name='imagem',
            name='cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cadastro'),
        ),
    ]
