# Generated by Django 4.1.7 on 2023-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_remove_cadastro_imagens_imagem_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
